# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DBA MultiTool
email: john@lowlydba.com
description: A suite of T-SQL utility scripts for Microsoft SQL Server.
baseurl: "/hyperspace-jekyll-theme/" # the subpath of your site, e.g. /blog
url: "https://lowlydba.gitlab.io" # the base hostname & protocol for your site

# Social settings
500px_url: 
facebook_url:
github_url: https://github.com/LowlyDBA
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/LowlyDBA

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: LowlyDBA
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
